# Generated by Django 5.0.8 on 2024-09-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
